FROM docker.io/riscv64/ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y \
    build-essential \
    clang \
    llvm \
    lld-14 \
    cmake \
    ninja-build \
    git && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /root
CMD ["bash"]
